// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mini
Rcpp::List mini(Rcpp::List data);
RcppExport SEXP migration_mini(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = mini(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev3
Rcpp::List dev3(Rcpp::List data);
RcppExport SEXP migration_dev3(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev3(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev2
Rcpp::List dev2(Rcpp::List data);
RcppExport SEXP migration_dev2(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev2(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev1
Rcpp::List dev1(Rcpp::List data);
RcppExport SEXP migration_dev1(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev1(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// devC
Rcpp::List devC(Rcpp::List data);
RcppExport SEXP migration_devC(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = devC(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
