// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dev_blitz1
Rcpp::List dev_blitz1(Rcpp::List data);
RcppExport SEXP migration_dev_blitz1(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev_blitz1(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev_blitz2
Rcpp::List dev_blitz2(Rcpp::List data);
RcppExport SEXP migration_dev_blitz2(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev_blitz2(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev7
Rcpp::List dev7(Rcpp::List data);
RcppExport SEXP migration_dev7(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev7(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev6
Rcpp::List dev6(Rcpp::List data);
RcppExport SEXP migration_dev6(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev6(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev5
Rcpp::List dev5(Rcpp::List data);
RcppExport SEXP migration_dev5(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev5(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev4
Rcpp::List dev4(Rcpp::List data);
RcppExport SEXP migration_dev4(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev4(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev3H
Rcpp::List dev3H(Rcpp::List data);
RcppExport SEXP migration_dev3H(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev3H(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev3
Rcpp::List dev3(Rcpp::List data);
RcppExport SEXP migration_dev3(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev3(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev2
Rcpp::List dev2(Rcpp::List data);
RcppExport SEXP migration_dev2(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev2(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev2a
Rcpp::List dev2a(Rcpp::List data);
RcppExport SEXP migration_dev2a(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev2a(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dev1
Rcpp::List dev1(Rcpp::List data);
RcppExport SEXP migration_dev1(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = dev1(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// devC
Rcpp::List devC(Rcpp::List data);
RcppExport SEXP migration_devC(SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::List data = Rcpp::as<Rcpp::List >(dataSEXP);
        Rcpp::List __result = devC(data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
