# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Blitz mini discrete choice model
#'
#' @examples
#' x  <- sample(1:120,size=120,replace=F)
#' option1 <- array(x[1:60],c(2,5,6))
#' option2 <- array(x[61:100],c(2,5,6))
#' savings  <- array(runif(n=60),c(2,5,6))
#' dataR <- list(option1 = option1, option2 = option2, savings=savings)
#' blitz <- mini(data=dataR)
#' print(blitz)
#' r = list()
#' As <- option1 - savings
#' A2s <- option2 - savings
#' V1 = apply(As,c(1,2),max)
#' V2 = apply(A2s,c(1,2),max)
#' V12 = array(c(V1,V2),c(2,5,2))
#' r$vmax = apply(V12,c(1,2),max)
#' r$dchoice = apply(V12,c(1,2),which.max)
#'	print(all.equal(r,blitz))
mini <- function(data) {
    .Call('migration_mini', PACKAGE = 'migration', data)
}

#' dev4
#'
#' @examples
#' nA <- 5L; nY <- 3L; nT <- 3L
#' s <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT))
#' s[,cash1 := a + y + 0.3*it]
#' s[,cash2 := a + y + 0.2*it + 0.09*it^2]
#' save <- seq(0,10,length=nA)
#' ss <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT,save=save))
#' ss[,cons1 := a + y + 0.3*it - save]
#' ss[,cons2 := a + y + 0.2*it + 0.09*it^2 - save]
#' dataR <- list( cash1 = s[["cash1"]],
#'                cash2 = s[["cash2"]],
#'                dims = c(nA,nY,nT),
#'                savings = save,
#'                theta = 1.2,beta=0.95,myNA=-99)
#' blitz <- dev4(data=dataR)
#' 
#' ######################################################
#' # Calculating an R solution to this 3-period lifecycle
#' # with discrete choice in periods 1 and 2.
#' ######################################################
#' 
#'	V = array(0,c(nA,nY,nT))  # max( v1, v2 )
#'	D = array(0,c(nA,nY,nT))  # which.max( v1, v2 )
#'	v1 = array(0,c(nA,nY,nT))
#'	v2 = array(0,c(nA,nY,nT))
#'	S1 = array(0,c(nA,nY,nT))
#'	S2 = array(0,c(nA,nY,nT))
#'	V[ , ,3] = s[it==3,log(cash1)]
#' C1 = ss[,array(cons1,c(nA,nY,nT,nA))]
#' C2 = ss[,array(cons2,c(nA,nY,nT,nA))]
#' 
#' W1 = array(0,c(nA,nY,nT,nA))
#' W2 = array(0,c(nA,nY,nT,nA))
#' for (ti in 2:1) {
#'     for (ia in 1:nA) {
#'          for(iy in 1:nY) {
#'              for (ja in 1:nA){
#' 				 # optimal cons option 1
#'                  if (C1[ia,iy,ti,ja] > 0){
#' 		     		W1[ia,iy,ti,ja] = log(C1[ia,iy,ti,ja]) + dataR$beta*V[ja,iy,ti+1]
#' 			     } else {
#' 			        W1[ia,iy,ti,ja] = dataR$myNA
#' 			     }
#' 				 # optimal cons option 2
#'                  if (C2[ia,iy,ti,ja] > 0){
#' 		     		W2[ia,iy,ti,ja] = log(C2[ia,iy,ti,ja]) + dataR$beta*V[ja,iy,ti+1]
#' 			     } else {
#' 			        W2[ia,iy,ti,ja] = dataR$myNA
#' 			     }
#' 		     }
#' 			v1[ia,iy,ti] = max(W1[ia,iy,ti, ])
#' 			S1[ia,iy,ti] = which.max(W1[ia,iy,ti, ])
#' 			v2[ia,iy,ti] = max(W2[ia,iy,ti, ])
#' 			S2[ia,iy,ti] = which.max(W2[ia,iy,ti, ])
#'				V[ia,iy,ti] = max(v1[ia,iy,ti], v2[ia,iy,ti])
#'				D[ia,iy,ti] = which.max(c(v1[ia,iy,ti], v2[ia,iy,ti]))
#'	         }
#'	     }
#'	}
#' Cstar1 = array( C1[ cbind(1:(nA*nY*nT), as.numeric(S1) ) ], c(nA,nY,nT))
#' Cstar2 = array( C2[ cbind(1:(nA*nY*nT), as.numeric(S2) ) ], c(nA,nY,nT))
#' CstarBlitz1 = array( C1[ cbind(1:(nA*nY*nT), as.numeric(blitz$save1) ) ], c(nA,nY,nT))
#' CstarBlitz2 = array( C2[ cbind(1:(nA*nY*nT), as.numeric(blitz$save2) ) ], c(nA,nY,nT))
#' ############################################
#' # comparing R and blitz++ solutions
#' ############################################
#' 
#' print(all.equal(V,blitz$V))
#' print(all.equal(C1,blitz$cons1))
#' print(all.equal(C2,blitz$cons2))
#' print(all.equal(v1,blitz$v1))
#' print(all.equal(v2,blitz$v2))
#' print(all.equal(S1,blitz$save1))
#' print(all.equal(S2,blitz$save2))
#' print(all.equal(Cstar1,CstarBlitz1))
#' print(all.equal(Cstar2,CstarBlitz2))
dev4 <- function(data) {
    .Call('migration_dev4', PACKAGE = 'migration', data)
}

#' dev3
#'
#' @examples
#' nA <- 5L; nY <- 3L; nT <- 3L
#' s1 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT))
#' s1[,cash := a + y + 0.3*it]
#' save <- seq(0,10,length=nA)
#' s3 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT,save=save))
#' s3[,cons := a + y + 0.3*it - save]
#' dataR <- list( cash1 = s1[["cash"]],
#'                dims = c(nA,nY,nT),
#'                savings = save,
#'                theta = 1.2,beta=0.95,myNA=-99)
#' blitz <- dev3(data=dataR)
#' 
#' ######################################################
#' # Calculating an R solution to this 3-period lifecycle
#' ######################################################
#' 
#' V = array(0,c(nA,nY,nT))
#' V[ , ,3] = s1[it==3,log(cash)]
#' C = s3[,array(cons,c(nA,nY,nT,nA))]
#' W = array(0,c(nA,nY,nT,nA))
#' for (ti in 2:1) {
#'     for (ia in 1:nA) {
#'          for(iy in 1:nY) {
#'              for (ja in 1:nA){
#'                  if (C[ia,iy,ti,ja] > 0){
#' 		     		W[ia,iy,ti,ja] =  log(C[ia,iy,ti,ja])  + dataR$beta*V[ja,iy,ti+1]
#' 			     } else {
#' 			        W[ia,iy,ti,ja] = dataR$myNA
#' 			     }
#' 		     }
#' 			V[ia,iy,ti] = max(W[ia,iy,ti, ])
#'          }
#'      }
#'	}
#' ############################################
#' # comparing R and blitz++ solutions
#' ############################################
#' 
#' print(all.equal(V,blitz$V1))
#' print(all.equal(W[ , ,1, ],blitz$w))
#' print(all.equal(C,blitz$cons))
dev3 <- function(data) {
    .Call('migration_dev3', PACKAGE = 'migration', data)
}

#' dev2
#'
#' @examples
#' nA <- 5L; nY <- 3L; nT <- 3L
#' s1 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT))
#' s1[,cash := a + y + 0.3*it]
#' s2 <- copy(s1)
#' s2[,cash := a + y + 0.2*it + 0.09*it^2]
#' save <- seq(0,10,length=nA)
#' dataR <- list( cash1 = s1[["cash"]],
#'                cash2 = s2[["cash"]],
#'                dims = c(nA,nY,nT),
#'                savings = save,
#'                theta = 1.2,beta=0.95,myNA=-99)
#' blitz <- dev2(data=dataR)
#' V1_R = s1[,array(cash,c(nA,nY,nT))]
#' V1_R[ , ,3] = log(V1_R[ , ,3])
#' for (ti in 2:1) {
#'     for (ia in 1:nA) {
#'          for(iy in 1:nY) {
#'				if (V1_R[ia,iy,ti]<0) {
#'					V1_R[ia,iy,ti] <- dataR$myNA
#'				} else {
#'					V1_R[ia,iy,ti] = log(V1_R[ia,iy,ti]) + dataR$beta*V1_R[ia,iy,ti+1]
#'				}
#'          }
#'      }
#' }
#' print(all.equal(V1_R,blitz$V1))
dev2 <- function(data) {
    .Call('migration_dev2', PACKAGE = 'migration', data)
}

#' dev1
#'
#' @examples
#' nA <- 5L; nY <- 3L; nT <- 3L
#' s1 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT))
#' s1[,cash := a + y + 0.3*it]
#' s2 <- copy(s1)
#' s2[,cash := a + y + 0.2*it + 0.09*it^2]
#' save <- seq(0,10,length=nA)
#' dataR <- list( cash1 = s1[["cash"]],
#'                cash2 = s2[["cash"]],
#'                dims = c(nA,nY,nT),
#'                savings = save,
#'                theta = 1.2)
#' blitz <- dev1(data=dataR)
#' print(all.equal(s1[it==3,array(log(cash),c(nA,nY))],blitz$V1[ , ,3]))
dev1 <- function(data) {
    .Call('migration_dev1', PACKAGE = 'migration', data)
}

#' devC
#'
#' @examples
#' nA <- 5L; nY <- 3L; nT <- 3L
#' s1 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT))
#' s1[,cash := a + y + 0.3*it]
#' s2 <- copy(s1)
#' s2[,cash := a + y + 0.2*it + 0.09*it^2]
#' save <- seq(0,10,length=nA)
#' dataR <- list( cash1 = s1[["cash"]],
#'                cash2 = s2[["cash"]],
#'                dims = c(nA,nY,nT),
#'                savings = save)
#' blitz <- devC(data=dataR)
#' s3 <- data.table(expand.grid(a=seq(0,10,length=nA),y=1:nY,it=1:nT,save=save))
#' s3[,cons := a + y + 0.3*it - save]
#' print(all.equal(s3[,array(cons,c(nA,nY,nT,nA))],blitz$vmax))
devC <- function(data) {
    .Call('migration_devC', PACKAGE = 'migration', data)
}

