# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Blitz mini discrete choice model
#'
#' in this example we map actually arrays from R to C++
#' Arrays are vectors with a dimension attribute
#' @example examples/example-blitz1.r
dev_blitz1 <- function(data) {
    .Call('migration_dev_blitz1', PACKAGE = 'migration', data)
}

#' Blitz mini discrete choice model 2
#'
#' in this example we map vectors to C
#' @example examples/example-blitz2.r
dev_blitz2 <- function(data) {
    .Call('migration_dev_blitz2', PACKAGE = 'migration', data)
}

#' dev7: discrete optimization, housing choice, utility function
#' 
#' @example examples/example-dev7.r
dev7 <- function(data) {
    .Call('migration_dev7', PACKAGE = 'migration', data)
}

#' dev6: discrete optimization, housing choice
#' 
#' @example examples/example-dev6.r
dev6 <- function(data) {
    .Call('migration_dev6', PACKAGE = 'migration', data)
}

#' dev5: discrete optimization, housing choice
#' 
#' @example examples/example-dev5.r
dev5 <- function(data) {
    .Call('migration_dev5', PACKAGE = 'migration', data)
}

#' dev4
#'
#' @example examples/example-dev4.r
dev4 <- function(data) {
    .Call('migration_dev4', PACKAGE = 'migration', data)
}

#' dev3H
#'
#' @example examples/example-dev3H.r
dev3H <- function(data) {
    .Call('migration_dev3H', PACKAGE = 'migration', data)
}

#' dev3
#'
#' @example examples/example-dev3.r
dev3 <- function(data) {
    .Call('migration_dev3', PACKAGE = 'migration', data)
}

#' dev2
#'
#' @example examples/example-dev2.r
dev2 <- function(data) {
    .Call('migration_dev2', PACKAGE = 'migration', data)
}

#' dev2a
#'
#' @example examples/example-dev2a.r
dev2a <- function(data) {
    .Call('migration_dev2a', PACKAGE = 'migration', data)
}

#' dev1
#'
#' @example examples/example-dev1.r
dev1 <- function(data) {
    .Call('migration_dev1', PACKAGE = 'migration', data)
}

#' devC
#'
#' @example examples/example-devC.r
devC <- function(data) {
    .Call('migration_devC', PACKAGE = 'migration', data)
}

#' dev8: discrete optimization, housing choice, utility function, location choice
#' 
#' @example examples/example-dev8.r
dev8 <- function(data) {
    .Call('migration_dev8', PACKAGE = 'migration', data)
}

#' dev9: continuous optimization, utility function
#' 
#' @example examples/example-dev10.r
dev9 <- function(data) {
    .Call('migration_dev9', PACKAGE = 'migration', data)
}

